language: node_js
sudo: false

node_js:
  - "4"
  - "6"
  - "8"

before_script:
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.0.4/gnatsd-v1.0.4-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v1.0.4-linux-amd64 gnatsd

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 4 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 6 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 8 ]]; then npm run coveralls; fi

after_failure:
  - cat "/tmp/test_ports.txt"